# Generated by Django 4.2.1 on 2023-06-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
